name: Upload ETL Script & Trigger Job

on:
  push:
    branches:
      - main  # or 'main' based on your use case

jobs:
  upload-and-run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Optional if you're using temporary credentials
          aws-region: ${{ secrets.REGION }}

      - name: Upload latest ETL script to S3
        run: |
          aws s3 cp statified_sample_data1.csv s3://trans123321/statified_sample_data1.csv
